# Log Query Notebook

In [20]:
import pandas as pd

LOG_PATH = "../typhoon/output_data/master_summary_log.csv"

In [21]:
""" Preview Dataframe """

log_df = pd.read_csv(LOG_PATH)
log_df

,tambon,unit,type,file,needs_manual_check,flag_math_total_used,flag_math_valid_score,flag_name_mismatch,details
0,ตำบลแก่นมะกรูด,หน่วยเลือกตั้งที่ 1,บัญชีรายชื่อ,ส.ส.5ทับ18 (บช.).pdf,True,False,True,True,บัตรดี(270) != รวมคะแนน(267)
1,ตำบลแก่นมะกรูด,หน่วยเลือกตั้งที่ 1,แบ่งเขต,ส.ส.5ทับ18.pdf,True,False,True,True,บัตรดี(254) != รวมคะแนน(0)
2,ตำบลแก่นมะกรูด,หน่วยเลือกตั้งที่ 2,บัญชีรายชื่อ,ส.ส.5ทับ18 (บช.).pdf,True,True,True,True,บัตรใช้(285) != รวมย่อย(0) | บัตรดี(0) != รวมค...
3,ตำบลแก่นมะกรูด,หน่วยเลือกตั้งที่ 2,แบ่งเขต,ส.ส.5ทับ18.pdf,True,True,True,True,บัตรใช้(300) != รวมย่อย(250) | บัตรดี(200) != ...
4,ตำบลแก่นมะกรูด,หน่วยเลือกตั้งที่ 4,บัญชีรายชื่อ,ส.ส.5ทับ18 (บช.).pdf,True,False,True,True,บัตรดี(321) != รวมคะแนน(374)
5,ตำบลแก่นมะกรูด,หน่วยเลือกตั้งที่ 4,แบ่งเขต,ส.ส.5ทับ18.pdf,True,False,True,True,บัตรดี(340) != รวมคะแนน(0)
6,ตำบลแก่นมะกรูด,หน่วยเลือกตั้งที่ 3,บัญชีรายชื่อ,ส.ส.5ทับ18 (บช.).pdf,True,False,True,True,บัตรดี(341) != รวมคะแนน(351)
7,ตำบลแก่นมะกรูด,หน่วยเลือกตั้งที่ 3,แบ่งเขต,ส.ส.5ทับ18.pdf,True,True,True,True,บัตรใช้(375) != รวมย่อย(415) | บัตรดี(378) != ...

In [22]:
""" Data that needs MANUAL check """

log_manual_ck_df = log_df[log_df['needs_manual_check'] == 1]
log_manual_ck_df

,tambon,unit,type,file,needs_manual_check,flag_math_total_used,flag_math_valid_score,flag_name_mismatch,details
0,ตำบลแก่นมะกรูด,หน่วยเลือกตั้งที่ 1,บัญชีรายชื่อ,ส.ส.5ทับ18 (บช.).pdf,True,False,True,True,บัตรดี(270) != รวมคะแนน(267)
1,ตำบลแก่นมะกรูด,หน่วยเลือกตั้งที่ 1,แบ่งเขต,ส.ส.5ทับ18.pdf,True,False,True,True,บัตรดี(254) != รวมคะแนน(0)
2,ตำบลแก่นมะกรูด,หน่วยเลือกตั้งที่ 2,บัญชีรายชื่อ,ส.ส.5ทับ18 (บช.).pdf,True,True,True,True,บัตรใช้(285) != รวมย่อย(0) | บัตรดี(0) != รวมค...
3,ตำบลแก่นมะกรูด,หน่วยเลือกตั้งที่ 2,แบ่งเขต,ส.ส.5ทับ18.pdf,True,True,True,True,บัตรใช้(300) != รวมย่อย(250) | บัตรดี(200) != ...
4,ตำบลแก่นมะกรูด,หน่วยเลือกตั้งที่ 4,บัญชีรายชื่อ,ส.ส.5ทับ18 (บช.).pdf,True,False,True,True,บัตรดี(321) != รวมคะแนน(374)
5,ตำบลแก่นมะกรูด,หน่วยเลือกตั้งที่ 4,แบ่งเขต,ส.ส.5ทับ18.pdf,True,False,True,True,บัตรดี(340) != รวมคะแนน(0)
6,ตำบลแก่นมะกรูด,หน่วยเลือกตั้งที่ 3,บัญชีรายชื่อ,ส.ส.5ทับ18 (บช.).pdf,True,False,True,True,บัตรดี(341) != รวมคะแนน(351)
7,ตำบลแก่นมะกรูด,หน่วยเลือกตั้งที่ 3,แบ่งเขต,ส.ส.5ทับ18.pdf,True,True,True,True,บัตรใช้(375) != รวมย่อย(415) | บัตรดี(378) != ...

# 1. ดูรายการที่มีปัญหาเรื่อง "ผลรวมจำนวนบัตร" (Math Total Used)
> [จำนวนบัตรที่ใช้] = [บัตรดี] + [บัตรเสีย] + [ไม่เลือกใคร]

In [23]:
math_used_fail = log_df[log_df['flag_math_total_used'] == True]
print(f"มีปัญหาผลรวมบัตร: {len(math_used_fail)} รายการ")
display(math_used_fail)

มีปัญหาผลรวมบัตร: 3 รายการ

,tambon,unit,type,file,needs_manual_check,flag_math_total_used,flag_math_valid_score,flag_name_mismatch,details
2,ตำบลแก่นมะกรูด,หน่วยเลือกตั้งที่ 2,บัญชีรายชื่อ,ส.ส.5ทับ18 (บช.).pdf,True,True,True,True,บัตรใช้(285) != รวมย่อย(0) | บัตรดี(0) != รวมค...
3,ตำบลแก่นมะกรูด,หน่วยเลือกตั้งที่ 2,แบ่งเขต,ส.ส.5ทับ18.pdf,True,True,True,True,บัตรใช้(300) != รวมย่อย(250) | บัตรดี(200) != ...
7,ตำบลแก่นมะกรูด,หน่วยเลือกตั้งที่ 3,แบ่งเขต,ส.ส.5ทับ18.pdf,True,True,True,True,บัตรใช้(375) != รวมย่อย(415) | บัตรดี(378) != ...

# 2. ดูรายการที่มีปัญหาเรื่อง "คะแนนรวมผู้สมัครไม่ตรงกับจำนวนบัตรดี" (Math Valid Score)

> [จำนวนบัตรดี] = [ผลรวมของคะแนนทุกพรรค/ผู้สมัครในตารางรวมกัน]

In [24]:
math_score_fail = log_df[log_df['flag_math_valid_score'] == True]
print(f"มีปัญหาคะแนนรวมไม่ตรงกับบัตรดี: {len(math_score_fail)} รายการ")
display(math_score_fail)

มีปัญหาคะแนนรวมไม่ตรงกับบัตรดี: 8 รายการ

,tambon,unit,type,file,needs_manual_check,flag_math_total_used,flag_math_valid_score,flag_name_mismatch,details
0,ตำบลแก่นมะกรูด,หน่วยเลือกตั้งที่ 1,บัญชีรายชื่อ,ส.ส.5ทับ18 (บช.).pdf,True,False,True,True,บัตรดี(270) != รวมคะแนน(267)
1,ตำบลแก่นมะกรูด,หน่วยเลือกตั้งที่ 1,แบ่งเขต,ส.ส.5ทับ18.pdf,True,False,True,True,บัตรดี(254) != รวมคะแนน(0)
2,ตำบลแก่นมะกรูด,หน่วยเลือกตั้งที่ 2,บัญชีรายชื่อ,ส.ส.5ทับ18 (บช.).pdf,True,True,True,True,บัตรใช้(285) != รวมย่อย(0) | บัตรดี(0) != รวมค...
3,ตำบลแก่นมะกรูด,หน่วยเลือกตั้งที่ 2,แบ่งเขต,ส.ส.5ทับ18.pdf,True,True,True,True,บัตรใช้(300) != รวมย่อย(250) | บัตรดี(200) != ...
4,ตำบลแก่นมะกรูด,หน่วยเลือกตั้งที่ 4,บัญชีรายชื่อ,ส.ส.5ทับ18 (บช.).pdf,True,False,True,True,บัตรดี(321) != รวมคะแนน(374)
5,ตำบลแก่นมะกรูด,หน่วยเลือกตั้งที่ 4,แบ่งเขต,ส.ส.5ทับ18.pdf,True,False,True,True,บัตรดี(340) != รวมคะแนน(0)
6,ตำบลแก่นมะกรูด,หน่วยเลือกตั้งที่ 3,บัญชีรายชื่อ,ส.ส.5ทับ18 (บช.).pdf,True,False,True,True,บัตรดี(341) != รวมคะแนน(351)
7,ตำบลแก่นมะกรูด,หน่วยเลือกตั้งที่ 3,แบ่งเขต,ส.ส.5ทับ18.pdf,True,True,True,True,บัตรใช้(375) != รวมย่อย(415) | บัตรดี(378) != ...

# 3. ดูรายการที่ "ชื่อผู้สมัคร/พรรค อ่านเพี้ยน" (Name Mismatch)

In [25]:
name_fail = log_df[log_df['flag_name_mismatch'] == True]
print(f"ชื่อไม่ตรงกับ Master List (Uthai Dist 2): {len(name_fail)} รายการ")
display(name_fail)

ชื่อไม่ตรงกับ Master List (Uthai Dist 2): 8 รายการ

,tambon,unit,type,file,needs_manual_check,flag_math_total_used,flag_math_valid_score,flag_name_mismatch,details
0,ตำบลแก่นมะกรูด,หน่วยเลือกตั้งที่ 1,บัญชีรายชื่อ,ส.ส.5ทับ18 (บช.).pdf,True,False,True,True,บัตรดี(270) != รวมคะแนน(267)
1,ตำบลแก่นมะกรูด,หน่วยเลือกตั้งที่ 1,แบ่งเขต,ส.ส.5ทับ18.pdf,True,False,True,True,บัตรดี(254) != รวมคะแนน(0)
2,ตำบลแก่นมะกรูด,หน่วยเลือกตั้งที่ 2,บัญชีรายชื่อ,ส.ส.5ทับ18 (บช.).pdf,True,True,True,True,บัตรใช้(285) != รวมย่อย(0) | บัตรดี(0) != รวมค...
3,ตำบลแก่นมะกรูด,หน่วยเลือกตั้งที่ 2,แบ่งเขต,ส.ส.5ทับ18.pdf,True,True,True,True,บัตรใช้(300) != รวมย่อย(250) | บัตรดี(200) != ...
4,ตำบลแก่นมะกรูด,หน่วยเลือกตั้งที่ 4,บัญชีรายชื่อ,ส.ส.5ทับ18 (บช.).pdf,True,False,True,True,บัตรดี(321) != รวมคะแนน(374)
5,ตำบลแก่นมะกรูด,หน่วยเลือกตั้งที่ 4,แบ่งเขต,ส.ส.5ทับ18.pdf,True,False,True,True,บัตรดี(340) != รวมคะแนน(0)
6,ตำบลแก่นมะกรูด,หน่วยเลือกตั้งที่ 3,บัญชีรายชื่อ,ส.ส.5ทับ18 (บช.).pdf,True,False,True,True,บัตรดี(341) != รวมคะแนน(351)
7,ตำบลแก่นมะกรูด,หน่วยเลือกตั้งที่ 3,แบ่งเขต,ส.ส.5ทับ18.pdf,True,True,True,True,บัตรใช้(375) != รวมย่อย(415) | บัตรดี(378) != ...

# 4. ดูรายการที่ "ผิดมากกว่า 1 อย่าง" (Multiple Failures)

In [26]:
multi_fail = log_df[
    (log_df['flag_math_total_used'] == True) & 
    (log_df['flag_math_valid_score'] == True)
]
print(f"Emer ! ผิดทั้งบัตรและคะแนน: {len(multi_fail)} รายการ")
display(multi_fail)

Emer ! ผิดทั้งบัตรและคะแนน: 3 รายการ

,tambon,unit,type,file,needs_manual_check,flag_math_total_used,flag_math_valid_score,flag_name_mismatch,details
2,ตำบลแก่นมะกรูด,หน่วยเลือกตั้งที่ 2,บัญชีรายชื่อ,ส.ส.5ทับ18 (บช.).pdf,True,True,True,True,บัตรใช้(285) != รวมย่อย(0) | บัตรดี(0) != รวมค...
3,ตำบลแก่นมะกรูด,หน่วยเลือกตั้งที่ 2,แบ่งเขต,ส.ส.5ทับ18.pdf,True,True,True,True,บัตรใช้(300) != รวมย่อย(250) | บัตรดี(200) != ...
7,ตำบลแก่นมะกรูด,หน่วยเลือกตั้งที่ 3,แบ่งเขต,ส.ส.5ทับ18.pdf,True,True,True,True,บัตรใช้(375) != รวมย่อย(415) | บัตรดี(378) != ...